ACTIVE_CHECK = "black"
INACTIVE_CHECK = "white"
CHECK_EDGE = "black"

TRUE_ERROR = "#d62728"
TRUE_ERROR_LIGHT = "#f8d7da"
BP_CORRECTION = "#ff7f0e"
ML_CORRECTION = "#1f77b4"

CYCLE = "#2ca02c"
TREE_EDGE = "#2b6cb0"
NON_TREE_EDGE = "#cfcfcf"
FAINT_EDGE = "#d8d8d8"
FAINT_NODE = "#bbbbbb"

ROOT_CHECK = ML_CORRECTION
UNSATISFIED_CHECK = BP_CORRECTION
